// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/AppLink.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
  }
}

export { }
